version: '3'

# This files purpose is to run the PHPunit tests locally.
# Install docker and docker compose and than just run:
# docker compose up

services:
  test-db:
    image: mariadb
    environment:
      MARIADB_DATABASE: wordpress-test
      MARIADB_ROOT_PASSWORD: wordpress-test
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 5s
      interval: 4s
      timeout: 5s
      retries: 5

  test-php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      test-db:
        condition: service_healthy
    links:
      - test-db
    volumes:
      - .:/app
    command: ["composer", "run-script", "test"]
