# .github/workflows/deploy_wordpress_test1.yml

name: Deploy to https://wordpress-test.event-federation.eu/

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: secrets.SSH_PRIVATE_KEY != '' && secrets.SSH_HOST_KEY != ''

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: mkdir ~/.ssh
      - run: echo "${{ secrets.SSH_HOST_KEY }}" > ~/.ssh/known_hosts
      - run: chmod 600 ~/.ssh/known_hosts
      - run: apt update && apt install -y openssh-client rsync
      - run: eval $(ssh-agent -s) && echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
      - run: rsync -avzr --delete ${{ github.workspace }}/ hosting187597@hosting187597.a2f96.netcup.net:~/wordpress-test.event-federation.eu/wp-content/plugins/
