# .github/workflows/deploy_wordpress_test1.yml

name: Deploy to https://wordpress-test.event-federation.eu/

on:
  workflow_dispatch:
    inputs:
      web_root_directory:
        description: wordpress-test.event-federation.eu
        required: true

jobs:
  deploy:
    <<: *deploy