# .github/workflows/deploy_wordpress_test1.yml

name: Deploy to https://wordpress-test.event-federation.eu/

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: secrets.SSH_PRIVATE_KEY != ''

    steps:
      - name: Checkout Repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install rsync
        run: apt-update && apt install -y rsync

      - name: Deploy via rsync
        uses: https://github.com/burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ~/wordpress-test.event-federation.eu/wp-content/plugins/activitypub-event-transformers
          remote_host: hosting187597.a2f96.netcup.net
          remote_user: hosting187597
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}


