name: PHPUnit

on:
  push:
    branches:
      - ci_mobilizon
  pull_request:

env:
  WP_TESTS_DIR: /workspace/wordpress-test-lib
  WP_CORE_DIR: /workspace/wordpress

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
      postgres:
        image: docker.io/postgis/postgis:15-3.4
        env:
          POSTGRES_USER: mobilizon
          POSTGRES_PASSWORD: mobilizon
          POSTGRES_DB: mobilizon
        cmd:
          - '-p 127.0.0.1:5432:5432'
      mobilizon:
        image: docker.io/framasoft/mobilizon
        env:
          MOBILIZON_INSTANCE_NAME: Mobilizon
          MOBILIZON_INSTANCE_HOST: localhost
          MOBILIZON_INSTANCE_LISTEN_IP: "127.0.0.1"
          MOBILIZON_INSTANCE_PORT: "4000"
          MOBILIZON_DATABASE_HOST: "127.0.0.1"
          MOBILIZON_DATABASE_PORT: "5432"
        cmd:
          - '-p 127.0.0.1:4000:4000'
    strategy:
      matrix:
        php-version: ['8.1']
    name: PHPUnit – PHP ${{ matrix.php-version }}
    env:
      extensions: mysql
      key: cache-v1
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - run: sleep 1
      - run: curl -L 127.0.0.1:4000