name: PHP Code Checker

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITHUB_TOKEN: ${{ env.COMPOSER_TOKEN }}

jobs:
  phpcs:
    name: PHP Code Checker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache Composer
        id: cache-composer
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ./vendor/
          key: cache-composer-3

      - name: Setup cache environment for PHP Extensions
        id: php-extensions-cache
        uses: https://github.com/shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, iconv, json, libxml, zip
          key: php-extensions-cache-v1

      - name: Cache PHP extensions
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer
        env:
          runner: self-hosted

      - name: Install Composer dependencies for PHP
        if: steps.cache-composer.outputs.cache-hit != 'true'
        uses: ramsey/composer-install@v3

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs
