name: PHP Code Checker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
    strategy:
      matrix:
        php-versions: ['8.1']
    name: Run PHP Code Checker
    env:
      extensions: mysql
      key: cache-v1
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache Composer
        id: cache-composer
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: vendor
          key: cache-composer-1

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer, cs2pr
        env:
          runner: self-hosted

      - name: Install Composer dependencies for PHP
        if: steps.cache-composer.outputs.cache-hit != 'true'
        uses: ramsey/composer-install@v3

      - run: composer config --list

      - name: Detect coding standard violations
        run: ./vendor/bin/phpcs