name: Unit Testing
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
    strategy:
      matrix:
        php-versions: ['8.1']
    name: Run phpunit tests
    env:
      extensions: mysql
      key: cache-v1
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer, cs2pr
        env:
          runner: self-hosted

      - name: Install Composer dependencies for PHP
        uses: ramsey/composer-install@v3

      - name: Detect coding standard violations
        run: phpcs