name: PHPStan Tests

on:
  push:
    branches:
      - phpstan

env:
  WP_TESTS_DIR: /workspace/wordpress-test-lib
  WP_CORE_DIR: /workspace/wordpress

jobs:
  phpstan:
    name: PHPStan for WordPress ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Cache WordPress Setup and installed plugins (Event plugins and ActivityPub plugin).
        id: cache-wordpress
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ${{ env.WP_CORE_DIR }}
            ${{ env.WP_TESTS_DIR }}
          key: cache-wordpress-67-5

      - name: Cache Composer
        id: cache-composer
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: |
            ./vendor/
          key: cache-composer-3

      - name: Setup cache environment for PHP Extensions
        id: php-extensions-cache
        uses: https://github.com/shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, iconv, json, libxml, zip
          key: php-extensions-cache-v1

      - name: Cache PHP extensions
        uses: https://code.forgejo.org/actions/cache@v4
        with:
          path: ${{ steps.php-extensions-cache.outputs.dir }}
          key: ${{ steps.php-extensions-cache.outputs.key }}
          restore-keys: ${{ steps.php-extensions-cache.outputs.key }}

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, iconv, json, libxml, zip
          coverage: none
          tools: composer, cs2pr
        env:
          runner: self-hosted
          GITHUB_TOKEN: ${{ env.COMPOSER_TOKEN }}

      - name: Install Composer dependencies for PHP
        if: steps.cache-composer.outputs.cache-hit != 'true'
        uses: ramsey/composer-install@v3
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.COMPOSER_TOKEN }}"}}'

      - name: Log debug information
        run: |
          git --version
          php --version
          composer --version

      - name: Install third party plugins, so that PHP Stan finds that functions
        if: steps.cache-wordpress.outputs.cache-hit != 'true'
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest true false false true

      - name: Running PHPStan Analyze
        if: ${{ success() || failure() }}
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyze -vv --memory-limit=2G --error-format=checkstyle | cs2pr
