name: Unit Testing
on:
  push:
    branches:
      - main
  pull_request:

env:
  WP_TESTS_DIR: /workspace/wordpress-test-lib/
  WP_CORE_DIR: /workspace/wordpress/

jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD: root
    strategy:
      matrix:
        php-versions: ['8.1']
    name: Run phpunit tests
    env:
      extensions: mysql
      key: cache-v1
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer, phpunit-polyfills

      - name: Install Composer dependencies for PHP
        uses: "ramsey/composer-install@v1"

      - name: Install mysqladmin
        run: sudo apt update && sudo apt -y upgrade && sudo apt -y install mysql-client

      - name: Clone plugin dependencies
        run: git clone https://code.event-federation.eu/Event-Federation/wordpress-activitypub.git $WP_CORE_DIR/wp-content/plugins/activitypub/

      - name: Setup Test Environment
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: Unit Testing
        run: cd /workspace/Event-Federation/wordpress-activitypub-event-extensions/ && phpunit
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
