name: Unit Testing
on:
  push:
  pull_request:
jobs:
  phpunit:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: 'mariadb:10.7'
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
        include:
          - wp-version: latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup PHP
        uses: https://github.com/shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          tools: composer, phpunit-polyfills
          extensions: mysql

      # - name: Install Composer dependencies for PHP
      #   uses: "ramsey/composer-install@v1"

      # - name: Setup Test Environment
      #   run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wp-version }}

      # - name: Unit Testing
      #   run: ./vendor/bin/phpunit
      #   env:
      #     PHP_VERSION: ${{ matrix.php-versions }}
