when:
  - event: push
    branch: woodpecker

steps:
  - name: build
    image: php:8.3
    environment:
      WP_TESTS_PHPUNIT_POLYFILLS_PATH: vendor/yoast/phpunit-polyfills
    commands:
      - apt -y update
      - apt -y install libonig-dev libicu-dev zlib1g zlib1g-dev libpng-dev libzip-dev bzip2 libbz2-dev subversion unzip
      - docker-php-ext-install mbstring mysqli pdo_mysql intl gd zip bz2
      - docker-php-ext-enable mbstring mysqli pdo_mysql intl gd zip bz2
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - composer require --dev yoast/phpunit-polyfills:"^3.0"
      - composer require --dev phpunit/phpunit ^11
      - composer install
      - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
      - ./vendor/bin/phpunit --configuration phpunit.xml.dist

services:
  - name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress_tests
      MYSQL_ROOT_PASSWORD: mysql