when:
  - event: push
    branch: woodpecker

steps:
  - name: build
    image: wordpressdevelop/phpunit
    environment:
      WP_TESTS_PHPUNIT_POLYFILLS_PATH: vendor/yoast/phpunit-polyfills
    commands:
      - apt-get clean
      - apt-get -yqq update
      - apt-get -yqqf install zip unzip subversion php8.3-mysql php8.3-bz2 php8.3-mcrypt
      - docker-php-ext-enable mbstring mcrypt mysqli pdo_mysql intl gd zip bz2
      - composer require --dev yoast/phpunit-polyfills:"^3.0"
      - composer install
      - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
      - phpunit --configuration phpunit.xml.dist


services:
  - name: database
    image: mysql
    environment:
      MYSQL_DATABASE: wordpress_tests
      MYSQL_ROOT_PASSWORD: mysql